services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
    ports:
      - '27017:27017'
    volumes:
      - mongodb_data:/data/db
    networks:
      - nest-starter-network
# development environment
  dev:
    container_name: nest-starter_dev_api
    build:
      context: .
      dockerfile: ./Dockerfile
      target: development
    command: npm run start:dev
    ports:
      - ${PORT}:${PORT}
      # - 9093:9093
    env_file:
      - .env # ensure the required variables are initialized
      # - .env.test # you can also read from file
    environment:
      - NODE_ENV=development
    networks:
      - nest-starter-network
    # volumes:
    #   - .:/app
    #   - ./app/node_modules
    restart: unless-stopped
    depends_on:
      - mongodb

# production environment
  prod:
    container_name: nest-starter_prod_api
    build:
      context: .
      dockerfile: ./Dockerfile
      target: production
    command: npm run start:prod
    ports:
      - ${PORT}:${PORT}
      # - 9093:9093
    env_file:
      - .env
    environment:
      - NODE_ENV=production
    networks:
      - nest-starter-network
    # volumes:
    #   - .:/app
    #   - ./app/node_modules
    restart: unless-stopped
    depends_on:
      - mongodb

volumes:
  mongodb_data:

networks:
  nest-starter-network:
